---
title: "Past Work"
format: html
editor: visual
---

[HOME](https://lsaiz07.github.io/mywebsite_saiz/)

## Past Work

This is a paper about the 2022 Florida Gubernatorial Race

In the morning of November 9^th^, there was a new political reality in the US. The red wave that analyst had predicted turned to be a red mirage. I have always considered the mid-term elections as secondary, less important than the Presidential, but this one was the most important midterm election in my lifetime. The results would be critical for the Biden administration in the next two years, but most importantly it would serve as a great predicter of the upcoming 2024 presidential elections. I believed that with Republicans making progress among the Latino and Black voters, they were poised to take back the White House in 2024.  However, after November 8^th^, I am having serious doubts. I see no way that the Republicans can win a Presidential election with poor performances in Wisconsin, Pennsylvania and Michigan. They need at least two of those states to win the electoral college. However, if the there was a bright spot for Republicans it was definitely Florida. Both Marco Rubio and Ron DeSantis won their respective election by much larger margins than anticipated.

The recent reelection of Ron DeSantis as Governor of Florida has marked an important shift in the state's political and electoral trends. Just to mention a quick fact, Miami-Dade county had not voted for a Republican in the last 20 years and the once democratic stronghold seems to be crumbling and turning red.

With DeSantis winning by an overwhelming margin of close to 60% of the vote shows that the future outlook of elections might be starting to change, and that political trends that were once believed to be set in stone, are starting to dissipate. This will certainly impact the way that the Democratic and Republican establishment target voters in upcoming elections. The Republican establishment will most likely give strong consideration to a DeSantis Presidential ticket, as his win in Florida clearly shows that he can turn what were once considered roadblocks for the Republican party into a strong voter base.  

# Demographics in Florida:

Florida as far as I can remember had been the poster boy for a swing state. I grew up listening to my father talk about the 2000 Presidential election, where 537 votes in Palm Beach County decided the result in a country of over 280 million people (remember the contested election, the "butterfly ballot" and hanging chats in Palm Beach County). That is less people than what fits in an A380 deciding the fate of the most powerful nation in the world.

Florida is a very unique state in terms of political demographics. With 21.7 million residents it is the third most populous state in the country. It also has a unique composure of residents that have a significant impact on electoral outcomes in the state.

Florida is often seen as a state for "retirees" or one where old people generally spend the last years of their lives, making Florida one of the "oldest" states when measuring by median age with 42.2 years (World Population Review). This is generally an important indicator when predicting electoral results. Older citizens tend to be active voters and actively participate in elections. According to Campaigns and Elections Ch. 12, "43% of people ages 18-24 reported voting compared with 71% of those 65 and over" (Sides et. al). In Florida, this is a big portion of the population. Older voters also tend to be more conservative in their political views. This is generally a bright spot for Republicans in Florida who see the state as contested but know that there is a group of voters that are consistently conservative.

Another important aspect of voter demographics is the concept of voter ethnicity. Once again, Florida is very unique amongst all other states. The two most populous counties of the state (Miami-Dade & Broward), have a significant Hispanic population that accounts for over 71% (Miami-Dade) and 30.2% (Broward) of the county's residents. One would assume under the traditional criteria, that the more Hispanic voters a State has, the better the possibilities for Democratic candidates. Florida is the complete opposite. Florida had 18.6 million people in 2009 and today, over 22 million. The Hispanic population was 20.5% in 2009 and today is 24.7%. However, as the Hispanic population has grown, the better Republicans have performed statewide.

The best example of this change has been Miami-Dade County, Florida's largest county, with 71% Hispanics. In the last 20 years all the governor and Presidential races have been blue. As an example Hillary Clinton won this county in 2016 by almost 30%, even though she lost the State. This all changed on November 8^th^, when DeSantis won Miami Dade by 11 percentage points. 

Ron DeSantis was able to get a large portion of the Hispanic vote by characterizing Democrats as Socialist. Many of the Hispanics in South Eastern Florida have left their countries of origin because of left wing governments that have bankrupted their economies. So the message from the DeSantis and Rubio campaigns resonated and scared Hispanic voters. Most of them voted against their party and switched from Democrats to Republicans (NBC).

The numbers show that historically, Hispanic voters have favored democrats in elections. As Erikson and Tedin explain in their writing, "Hispanics are more liberal than whites" (Erikson and Tedin). But this is a factor that while specific to counties in south eastern Florida, seems to be changing at a rapid pace. This particular group of voters while more liberal than the white rural voters of the state, is quickly transitioning their political views and challenging the previously assumed theories that Hispanic voters are a solid win for the Democratic party.

# Political Geography:

Historically, a challenge for both parties has been to breach the rural / urban divide in elections. Democratic campaigns have always attempted to increase their performance in rural areas while the Republicans have tried to improve theirs in cities. In Florida, while there is not a particularly strong political divide, there is still evidence of an ideological difference between those living in cities and those living in the country side. Major urban metropolises like Miami, Jacksonville, Tampa, and Orlando have a severe contrast with the rest of the state that tends to be a rural landscape. As we have learned in class and from past elections, urban settings generally favor democrats in elections while rural areas favor republicans. However, in DeSantis' reelection this month, this theory was challenged as there was no significant evidence of such a geographical divide.

In past elections such as the 2018 gubernatorial race, this trend was evident. Counties with major cities in them overwhelmingly voted for democrat Andrew Gillum while rural counties in the rest of the state voted for Governor Ron DeSantis. It was also clear in the 2020 Presidential race when counties like Miami-Dade, Duval, and Hillsborough, home to cities like Miami, Jacksonville, and Tampa respectively, voted majority democrat. This flip by the Governor's campaign was key to securing his victory as those counties could have made the race much more competitive.    

# Candidate Quality:

An important factor to consider when analyzing an electoral outcome is candidate quality. In the recent mid-term election, it is evident that candidate quality was at the top of the mind of many voters and top political operatives. This was evident by Democrats funding MAGA candidates to try and make them loose in the general election and by Sen. Mitch McConnell publicly stating that republicans had an issue with candidate quality. Elections like the Pennsylvania Senate race and the Arizona gubernatorial race are clear examples where candidates with cleaner records tended to perform better. The concept of split-ticket voting was a clear indication of this trend. According to Vox's Christian Paz, "MAGA true believers severely underperformed other Republicans on the ballot because of political inexperience, personal scandal, and lack of charisma" (Vox).

In the case of Ron DeSantis and his election in Florida, candidate quality was a potential threat that did not materialize as he is often seen as a controversial political figure. DeSantis was facing up against former Governor Charlie Crist who has a clean track record and no particular scandals threatening his performance in office.

On the other hand, in the run up to the election, DeSantis himself faced several situations that threatened to reverse his significant electoral win. One particular event that resonated across the country was the sudden transportation of migrants from Texas to Martha's Vineyard in Massachusetts. This political move by DeSantis was an attempt to advocate for stricter immigration laws. Nonetheless this was a dangerous move for DeSantis who evidently depended on the Hispanic vote for his victory. According to Erikson and Tedin, "Hispanics appear as the most liberal group only on immigration" (Erikson and Tedin) which highlights the importance of immigration policy to this ethnic group.

Another controversial move by DeSantis has been his war against "woke culture" across the state of Florida. Taking on corporate giants like Disney for their opposition of the "Parental Rights in Education" bill or more commonly known as the "Don't Say Gay" bill, drew a lot of backlash towards DeSantis and his policies. This however, was not a particularly risky move by DeSantis as his base voters tend to oppose liberal views on social issues. This is also the case with Hispanics and other minorities that tend to be conservative on these types of issues (Erikson and Tedin).

While hurricane Ian was a catastrophic storm that took an enormous amount of lives and cost millions of dollars in infrastructure, the storm provided an opportunity for DeSantis to appeal to undecided voters. While DeSantis and President Biden have disagreed for most of their tenures as executives, they showed a united front in response to the hurricane. While this might be something that is expected and taken for granted, it is important to remember that the country is currently undergoing a period of polarization like it never has since the Civil War and seeing DeSantis acting in such a proactive and non-partisan manner certainly convinced many independent and swing voters that he is the best choice for the job.

# Incumbency Advantage:

One of the strongest electoral patterns that exists is known as the incumbency advantage. This, as the name implies, is the idea that the candidate who is running for reelection has an advantage over the other candidate. As Ashworth and Bueno de Mesquita explain in their article, "elected politicians are extraordinarily successful when they seek reelection" (Ashworth & Bueno de Mesquita).

When analyzing the recent Florida gubernatorial race, it is important to understand that Ron DeSantis had a strong advantage coming into the race as an incumbent candidate. Nonetheless, incumbency does not necessarily guarantee an electoral victory. According to Jacobson, "the advent of a more polarized and loyal partisan electorate" (Jacobson), have started to challenge incumbency advantage in recent years. This election while very polarizing nationwide, proved to be favorable to DeSantis as Florida appeared to be united in his favor. Obtaining close to 60% of the vote, it is clear that the Governor had a strong performance that can in many ways be attributed to the incumbency advantage theory.

The incumbency advantage not only comes with a better performance when it comes to votes but also on many other electoral factors. As Professor Warshaw explained in class, incumbents generally have an easier time when it comes to fundraising. This, while not always the case, generally translates to a stronger result. In the case of DeSantis, his campaign has been the gubernatorial campaign with the highest funding in history, allowing him to have a significant advantage over Crist on TV ads across the state. According to a study by the Wesleyan Media Project, "DeSantis has held a 15:1 lead over Crist in broadcast advertising" (WMP). DeSantis also had a stronger performance in text message recruiting across the state and a stronger presence on social media and other means of communication. This generally translates to a higher voter turnout and potentially a stronger support for the candidate.

# Macro Factors:

For this election cycle there was much discussion of what would be in voters' minds when casting their vote. Some argued that the Supreme Court's decision to overturn Roe v Wade would mobilize the democratic base while others argued that issues such as inflation and crime would most likely favor republicans. In the case of Ron DeSantis, I believe that his firm stance on issues such as immigration, crime, and the economy favored him significantly. 

When analyzing the electoral outcome of counties such as Miami-Dade which has traditionally been a democratic stronghold, it is important to understand some of what has been going on in that area in recent years. Neighborhoods such as Miami Beach have seen an unprecedented rise in crime. According to Axios, crime in the city of Miami has increased by 4.2% from January 1^st^ to June 30^th^ of this year (Axios).

One particular issue that is specific to the state of Florida is the rise in home prices due to the large migration of people from cities in the north during the COVID-19 pandemic. This has inflated home prices in unprecedented rates and middle class families are struggling to cope. This is particularly important in the current political landscape since the high inflation has only made financial matters worse for Americans. DeSantis ran on an economic platform that highlighted the need to reduce costs on Floridians which is something that was definitely popular amongst voters in the state.

# Undecided Voters:

In any election one of the most important methods to ensure that a candidacy is successful, is to convince undecided, moderate voters that you are the right person for the job. When promoting their policies, candidates must have a full understanding of their intended audience and know that not everyone is going to be in favor of what they propose. They must also be aware of the constraints that their candidate profile imposes on them. As Sides et al explains, a candidate is not free to take any random position, a candidate must realize that their political ideology, either conservative or liberal must be reflected on their proposals. What is important is to decide whether to "take positions that are popular with citizens, or... seek to persuade citizens to adopt their point of view" (Sides et. Al).

This is particularly evident through what is known as the Median voter theorem which shows that the largest share of votes are those that are ideologically moderate in comparison with right and left wing radical voters. As opposed to the primaries, general election candidates benefit from having mostly moderate policy opinions as that's where they will find the most support. Hall explains how "primary voters exhibit a preference for more ideologically extreme candidates, but general election voters appear to prefer moderate" (Hall).

In the case of Ron DeSantis this had a particular influence on his election. As a candidate, DeSantis was aware that no matter what he said or proposed, his strong base of voters was never going to vote for Charlie Crist. However, he had a large share of voters that were undecided about who to elect as Governor. DeSantis was able to appeal to this group by promoting moderate policies on issues like climate where the Governor has frequently argued for protection of ecosystems such as the Florida wetlands and the restoration of the Florida Everglades.

For Florida voters particularly those living in waterfront areas their lives are formed around the water. Their income and hobbies usually have to do with the Intracoastal Water Way (ICWW) and one of the top concerns on their minds is the protection of this body of water. This might seem particularly inconsistent with the political profile of these voters as they are a majority Republican who are not firm believers in climate change. Nonetheless, when it comes to their ecosystems at home, they are particularly united in protecting them. The DeSantis campaign has used this to his advantage by promoting policies that will keep his base happy in said small communities, but also encourage undecided voters who are concerned about the environment to vote for him.

# Conclusion:

This election is one that I believe encompasses many of the concepts studied in class. Not only that but it also matches those concepts with a very particular state like Florida which has historically been very different from all other states. This cycle would have been significantly more competitive if many of the factors that came together to elect DeSantis had not taken place. Particularly the Hispanic vote which was most definitely the highlight of this election. It has symbolized a transition from traditional conceptions that had in the past challenged Republican candidates and which moving forward will now become one more voter group that is considered a "toss-up".

The election of Ron DeSantis in Florida is a microcosm of what the Republican party needs to achieve nationwide in order to gain political dominance in the future. It is clear that by appealing to only white rural voters, the party will no longer be able to win elections. However, it is also evident that groups of voters that were once believed to be solid democrats, such as Hispanics, are beginning to transition in their political opinions.

Finally DeSantis was very lucky that President Trump, saw him as a rival for 2024, and decided to attack and distance himself from him.  At this point, as it was reflected on November 8^th^, all the candidates in contested States that align with the MAGA message lost their elections. (i.e. Dr. OZ, Adam Laxalt, Blake Masters, Kari Lake). So I believe that by distancing himself from Trump, DeSantis can have a chance to win the White Suburban Female vote and other competitive voter groups in a future Presidential run. This would allow him to be very competitive in Michigan, Pennsylvania and Wisconsin, competitive states that are necessary to win a Presidential bid.

Now that Florida has gone from a toss-up State to solid Red, I believe that if DeSantis is able to reproduce the same messages that got him elected in Florida with the National Audience he might be able to carve out a significant portion of the Hispanic vote and White Suburban vote. This two voting groups would, in my opinion guarantee a Republican win in 2024.           

One other reason why I feel DeSantis is very well positioned for 2024, is that he starts the race with a "war chest" of over 90 million dollars left from his Gubernatorial campaign.  That is a significant advantage once the primaries begin! So even though we are still 714 days to the November 2024 elections, and in Politics this is an eternity during which many things can happen, I believe that at this time after the November 8^th^ elections, Ron DeSantis has become a very competitive candidate for the Republicans to win the White House back in 2024.

[Works Cited:]{.underline}

Ashworth, Scott, and Ethan Bueno de Mesquita. "Electoral Selection, Strategic Challenger Entry, and the Incumbency Advantage." *University of Chicago*, University of Chicago, Oct. 2008, <https://home.uchicago.edu/~sashwort/inc_adv.pdf>. 

"DeSantis Dominates Fl Gov Advertising." *Wesleyan Media Project*, Wesleyan University, 28 Sept. 2022, <https://mediaproject.wesleyan.edu/releases-092222/>.

Erikson, Robert S., and Kent L. Tedin. "Group Differences in Political Opinion." *American Public Opinion: Its Origins, Content, and Impact*, Routledge, 2019, pp. 192--199. 

Hall, Andrew B. "What Happens When Extremists Win Primaries?" *American Political Science Review*, vol. 109, no. 01, Feb. 2015, pp. 18--42. 

Jacobson, Gary C. "Its Nothing Personal: The Decline of the Incumbency Advantage in US House Elections." 9 Apr. 2018, pp. 861--873. 

"Median Age by State." *Median Age by State 2022*, <https://worldpopulationreview.com/state-rankings/median-age-by-state>.

Paz, Christian. "8 Questions the 2022 Midterms Answered." *Vox*, Vox, 14 Nov. 2022, <https://www.vox.com/2022/11/14/23456270/midterm-elections-2022-results-questions-trump-inflation-democracy>

Sides, J., Shaw, D. R., Grossmann, M., & Lipsitz, K. (2022). *Campaigns and elections: Rules, reality, strategy, choice*. W.W. Norton & Company, Inc. 

Vassolo, Martin. "Homicides Ebb in Miami-Dade, but Violent Crime Is Up." *Axios*, Axios, 20 Sept. 2022, <https://www.axios.com/local/miami/2022/09/20/miami-dade-homicides-violent-crime>.  

"Why Florida Latinos Turned out in Favor of Republicans." *NBCNews.com*, NBCUniversal News Group, 15 Nov. 2022, <https://www.nbcnews.com/news/latino/florida-latinos-turned-favor-republicans-rcna57167>.
