---
title: "Sample Paper"
format: html
editor: visual
---

This is a paper about the 2022 US Mid-Term Elections\
\
[*Predicting Elections: Not an Easy Task*]{.underline}

A few years ago, I read that predicting election results was a "fool's errand" as many factors can change the result just a few days before election night (Washington Post). Remember President Trump's *Access Hollywood* tape that came out a month before the 2016 Presidential elections? At the time his poll numbers dropped dramatically, and everyone thought his candidacy was dead. But just a few weeks later then FBI director James Comey sent a letter to Congress reviving the Hillary Clinton email scandal, causing her approval ratings to drop, and allowing Donald J. Trump to be elected President by a narrow margin. Had these two incidents not occurred, the Presidential election might have been very different and maybe Hillary Clinton would have been elected as the first female US President in history. This serves as a "disclaimer" in case the prediction I am about to present on who will take control of the Senate following next month's midterm elections is completely wrong.

Mid-Term elections are often a turning point in a presidential administration. They can have a significant influence on how much of the President's agenda is implemented. This year's Senate election is looking to be an incredibly close one. There are many controversial issues that are coming together to make a voter's choice very difficult. Historically, the President's party faces an uphill battle in mid-term elections. According to Skelley and Rakich, since WWII, the President's party performs an average of 7.4 points worse than it did two years prior. President Biden is not facing favorable conditions this cycle. He has an approval rating of about 41% and the economy is in a difficult spot. Despite this, I believe that Democrats have a better chance be it by a very small margin, to retain control of the Senate.

The 2022 mid-term elections are exceptionally competitive. There are three Senate races in particular that appear to be uniquely competitive and in my opinion will decide which party controls the senate. Those races in Pennsylvania, Georgia, and Nevada are all within margin of error in recent polls.

So far, most of the factors that usually predict an election such as the economy and Presidential approval are indicating that the Democrats will not have a successful election cycle. Inflation is close to a 40-year high at 8.3% and President Biden's approval is around 41%. Not a good spot to be heading into the midterms. However, there is a bright light that might show some promise for the Democrats this fall. According to Skelley and Rakich, an "indicator to watch ahead of the midterms is the result of special elections" (Skelley & Rakich). While these elections generally occur in very partisan districts, the win margins are good indicators of how each party will perform in the coming midterm election. Recently, democrats have performed particularly well in these races. In 2021 there were six US House special elections. Out of those six, Democrats overperformed in three raising doubts about a Republican wave this fall. Not only that, but this summer, Kansas had a statewide election, in which a larger than expected turnout of voters voted against a ballot measure that would have removed protections for abortion rights from the state's constitution and given to the legislature the ability to impose restrictions or ban abortion. It failed by 18 percentage points, or 165,000 votes statewide, in a traditionally conservative state (AP News).

While the Democrats might be facing some unfavorable situations heading into the elections, there is one particular factor that is in their favor. When predicting electoral success, an important element to take into consideration is candidate quality. This can range from previous scandals that a candidate has experienced to his or her political experience. In two of the three fundamental races (Pennsylvania and Georgia), candidate quality is a big issue for voters. In Pennsylvania, Republican Dr. Mehmet Oz is running against Democrat John Fetterman for the Senate seat. Both candidates have issues that make their qualifications for office questionable.

Dr. Oz is a Trump-backed candidate who is a celebrity medical doctor with no previous political experience. In recent years, political inexperience has become an increasingly common trend amongst candidates. Considering that the former President had no previous political experience and still received a significant portion of the voting share, it is easy to think that the issue of experience does not influence electoral results. However, research shows that previous-office experience does have an impact on voters decision. According to DeLuca, when newspapers are deciding who to endorse, they "often mention previous experience or relevant experience" when deciding on their endorsement (DeLuca). In the case of the Pennsylvania race, Oz is running against Fetterman who has previous public office experience working as the Lieutenant Governor for Pennsylvania. In addition, there have been voices of concern regarding the fact that Dr. Oz has not been a resident of Pennsylvania for more than just a few months and voters worry that he is detached from the daily lives and issues of Pennsylvania voters. While voters also have some doubt about Fetterman's fit for office particularly regarding his health after a recent stroke, at this time I believe that Fetterman will win the race by a very tight margin.

In Georgia, where football star Herschel Walker is running against incumbent Raphael Warnock, there is a similar situation taking place. In this case, not only does Walker lack political experience, but he has been involved in several scandals throughout the campaign trail. Particularly, Walker has been harmed by previous allegations of forced abortions with former partners. This is exceptionally harmful for him as a conservative candidate running on a pro-life platform in a Bible belt state.

When evaluating candidate quality, scandals are a useful factor to keep in mind as they usually have a significant impact on a candidates viability. According to Hamel and Miller, most candidates who have been embroiled in scandals face a voter decrease of about 6% to 11%. In an election as close as the one in Georgia, a difference such as that can have a detrimental effect on a candidate. This will particularly benefit the democratic candidate Warnock which polls show that he is only eight points ahead.

While Democrats are facing a difficult election this cycle, there are certain elements that are lining up to benefit them. This summer's Supreme Court ruling which overturned Roe V Wade, has been fundamental in increasing enthusiasm for Democrats. Historically, midterm elections have significantly less voter participation than Presidential elections. This is further enhanced by the fact that traditionally, voters from the President's party are less likely to turn out in the election. This concept defined by Skelley and Rakich as differential turnout explains that voters from the party not in power are more likely to turn out in mid-term elections. Furthermore, it is widely accepted that young college-aged voters who tend to be democrats, are less likely to turn out on elections (Sides, Shaw, Grossman, and Lipsitz).

Voter demographics for elections are clearly not in favor of Democrats. However, since the Dobbs decision, Democrats and particularly young democrats are showing a significant increase in voter enthusiasm ahead of the midterm elections. During Natalie Jackson's guest lecture on September 30^th^, Natalie showed how polls are highlighting the way that young democratic voters are becoming more passionate about the issues affecting them, particularly abortion. Not only that, but since the Dobbs decision, many states have reported record voter registration numbers for this cycle. This, I believe will help Democrats come election day.

This election will most likely not be decided on election night. Close elections might lead to recounts and there is a small chance of a run-off election in Georgia. However, no matter how small the margins are, it is critical for democracy that the election results, when final, are accepted. Questioning an election like President Trump did in 2020 has shown to have detrimental effects on public electoral trust.

Most evidence shows that the deck is stacked against Democrats in the 2022 Midterm elections. However, small but significant factors that affect the way that voters behave in elections are showing that Democrats might not have the disastrous election that was predicted one year ago. Don't get me wrong, there are many issues not discussed in this paper that still challenge my prediction. The economy is not performing well, gas prices are soaring once again, there is a strong feeling that crime has surged in the past two years, and the situation at the southern border regarding illegal immigration is at a historic high. Nonetheless, the Dobbs decision early this summer was a God-given gift for Democrats which experts believe significantly improved their chances of performing well in the Senate races this fall.

After all of the above analysis, it all boils down to simple math. If Democrats win Pennsylvania, which I think they will, they only need to win Nevada or Georgia to keep control of the Senate. I strongly believe that if the elections where to take place tomorrow there is a very good chance of Democrats retaining control of the Senate. However, two weeks in politics is an eternity and many things can happen between now and November 8^th^.

[Works Cited:]{.underline}

Jr, Thomas Richards. "Perspective \| Predicting the Outcome of the Election Is a Fool's Errand - Because of Contingency." *The Washington Post*, WP Company, 6 July 2020, <https://www.washingtonpost.com/outlook/2020/07/06/predicting-outcome-election-is-fools-errand-because-contingency/>.

Geoffrey Skelley & Nathaniel Rakich. "Why the President's Party Almost Always Has a Bad Midterm." *FiveThirtyEight*, FiveThirtyEight, 3 Jan. 2022, <https://fivethirtyeight.com/features/why-the-presidents-party-almost-always-has-a-bad-midterm/>.

DeLuca, Kevin. "Newspaper Endorsements, Candidate Quality, and Election Outcomes in the United States, 1950-2020." 

John Sides, Daron Shaw, Matt Grossmann, and Keena Lipsitz. Campaigns & Elections: Rules, Reality, Strategy (3rd Ed.).

Jackson, Natalie. "Polling." Guest Speaker: Natalie Jackson PRRI. Guest Lecture on Polling, 30 Sept. 2022, Washington DC, ZOOM. 

Hamel, Brian T., and Michael G. Miller. "How Voters Punish and Donors Protect Legislators Embroiled in Scandal." 

Hollingsworth, Heather. "Kansas Recount Confirms Results in Favor of Abortion Rights." *AP NEWS*, Associated Press, 24 Aug. 2022, <https://apnews.com/article/kansas-abortion-vote-recount-e874f56806a9d63b473b24580ad7ea0c>.  
