---
title: "Sample_paper2"
format: html
editor: visual
---

This is a paper about the role of media in American politics.

## It is difficult to find a country in the world where the media has more importance than it does in the United States. The institution is protected by the most sacred legal document, The Constitution, and it has many important roles in safeguarding American democracy. For a large part of history, the media was a partisan institution ran by party bosses who used newspapers to promote their opinions. When the penny press was rolled out, this changed. In an attempt to expand audience, news organizations began taking unbiased stances on policy focusing on objectivity and facts. Fast forward a century and there is a nearly record low trust in media at around 34% according to Gallup. The polls shows that only 7% of Americans have "a great deal" of trust and confidence in the media and about 38% have "none at all". This can be attributed to many factors, but one is chief amongst all, the notion that there is a "liberal bias" in the media.

            Liberal Bias in media is seen as favorable coverage of liberal personalities. This generally leads to reactions by conservative viewers who see media coverage as unfair or partisan. According to Budak et. al, media bias operates in two ways: through issue filtering and through issue framing (Budak et.al). This matter is difficult to properly detect and quantify as it is very much opinion based. However, it is critical to promote proper understanding of the problem since it is very clear that it contributes to polarization in America and it clearly has an impact on media trust leading consumers to seek information through less reliable and highly partisan sources that only confirm what they want to know / hear. 

            Media organizations should always strive for objectivity as this best benefits their goal of informing the American public. However, it is impossible to keep subjectivity out of every aspect of media making journalist's views and opinions evident in their work. For the most part, major news organizations such as CNN, MSNBC, the New York Times, and the Washington Post are composed of journalists sharing common trends. They are often educated, young, and work out of urban cities. According to Pew research, "highly educated adults -- particularly those who have attended graduate school -- are far more likely than those with less education to take predominantly liberal positions across a range of political values" (Pew). This profile of journalist, might often bleed their opinions into their work through unavoidable moments where subjectivity is shown. While educated readers might be able to understand this issue and realize that the majority of the story is made up of truth and objectivity, some might see this as a strategic liberal bias promoted by the news organization.

            All of the articles that I have consulted for this paper agree on one thing, the idea of a liberal bias within the media depends on who is asked. Generally, conservatives are often the first to point out that the media is biased against them. Several factors are known to contribute to their negative view of media organizations but one in particular is very much evident. In his article, David Jones explains how talk show radio has provided a safe haven for extreme conservatives who view the media as very biased. Shows like Rush Limbaugh, "frequently target news anchors and journalists" (Jones) promoting the idea of a liberal bias in media. It is important to understand that this has a very strong effect on the way that conservatives view traditional media sources and how much they trust them. Particularly it is important to know that conservative talk radio hosts benefit from the believe that there is a liberal media bias. The more radical conservatives distrust media, the more success their shows will have.

            When understanding the structure of media organizations it is important to differentiate between the "News" section of the publication as well as the "Opinion" section. As we learned in class, this is often difficult to distinguish for many readers or viewers. In their study, Budak et. al uses data to identify partisan bias from different news sources and differentiate their news section from their opinion section. The results clearly shows that there is an evident partisan bias in the opinion section but for the most part, news sections are mostly objective and free from any bias. News organizations however, must very clearly show the distinction between opinion and news. Failure to do so, often leads many consumers to assume that an opinion is the way that the organization frames a specific news story. This is very much wrong and a very dangerous assumption to make.

Modern sources of information such as internet sources also feed a specific group of users with unreliable news that is simply the opinion of those publishing such posts. This is a concept that resonates very much with the way that the media was structured in America before the Penny press. According to David Jones, different from the penny press model, internet sources are "narrowcast to small subsets of the population" (Jones), and act as a large forum or essentially a large opinion section for this group of readers. This leads extreme conservative and mostly uneducated people to view the media as a liberal organization and use these alternatives as a replacement for traditional media sources.

            One particular instance where it's possible to notice a partisan bias in the media is during political campaign season, particularly Presidential campaigns. During this time of high tensions in America where many opposing opinions are met with opposition, it is nearly impossible for the media to seem balanced to the American public. Any attack on one side will make that specific side feel like the organization is biased against their candidate and vice versa. However, in David Niven's article where he explains media coverage during elections, Niven argues that while there is a high support for the "notion that media are biased, little research has subjected these beliefs to meaningful tests" (Niven). Nonetheless, citizens and political bosses do not agree. In his article, Niven describes an instance when during the presidential election of George Bush, Republican National Committee leadership released the personal phone numbers of network news anchors to Republican activists across the country in protest against liberal bias in the media. They argued that the media constantly attacked conservative positions while positively framing liberal policies.

            Media bias is often an economic issue for media organizations. If they are considered highly partisan, they risk alienating a large portion of their audience. This is explained in Agirdas' article where he explains how local newspaper closings lead to more moderate and less partisan positions. In his article, Agirdas uses local Denver news as an example. The data shows that there where over 24 newspaper closings between 1990 and 2009. These organizations were for the most part objective but were still seen as partisan by certain readers. However, when one organization is closed, the remaining organizations attempt to broaden their coverage and framing to appeal to the readers of that former organization (Agirdas 2015). This often leads to a more moderate, less partisan reporting that reduces potential bias.

            The concept of liberal media bias mostly threatens national media organizations. Local news organizations also communicate information to many consumers and while they run a similar risk of appearing partisan, they are mostly vulnerable to claims of "conservative bias". In class we studied the Sinclair media group which is a media conglomerate that owns several local stations across the country. This organization is one that appeals mostly to conservative consumers as it is evident that their coverage is more conservative as part of "a persuasion effort" (Matthews). During the 2016 and 2020 elections as well as during Trump's tenure in office, Sinclair stations provided very sympathetic coverage of Trump's job as well as his policies to the point where Trump tweeted in their favor several times.

            Liberal media bias is a concept that is very difficult to identify and even harder to quantify. There are several pieces of evidence that point towards a bias in favor of liberal policies and personalities, but there are also many studies that show that as long as there are different political opinions, there will always be a believe that anyone who disagrees with one's opinion is biased against them. However, from what I have researched for this paper I believe that while conservatives are more common targets of media criticism, there is no strategic efforts by media organizations to support liberal political forces. It is clear that it all comes down to the question of objectivity vs subjectivity. The more objective a news organization is, the less vulnerable it will be to claims of political bias. However, as I explained earlier in this paper, there will always be some aspect of subjectivity, which often shows a liberal lean in their position. As Eisenger explains in his article, subjectivity is a "product of subconscious acts by liberals who think that liberalism is part of the political mainstream, whereas conservatism is an ideological extreme" (Eisenger). This is what drives many to believe that media organizations are biased towards liberal positions.

            In my opinion, the institution of the media is critical to the survival of American democracy. In a country as politically polarized as the US, it is unavoidable that certain claims of bias will arise. However, the public must be aware that media organizations do not benefit from being highly partisan, and in fact are extremely harmed by it. It is also critical for Americans to be aware of the risks of politically extreme media such as talk shows like Rush Limbaugh and Alex Jones whose platforms take advantage of confirmation bias or the idea that people seek confirmation of their beliefs to promote extreme and dangerous ideologies. As we have seen in recent years, through events like the January 6 insurrection, this will only risk American democracy and lead to a more polarized environment which only debilitates trust in traditional media and in American institutions.

[Works Cited:]{.underline}

Brenan, Megan. "Americans' Trust in Media Remains near Record Low." *Gallup.com*, Gallup, 17 Nov. 2022, <https://news.gallup.com/poll/403166/americans-trust-media-remains-near-record-low.aspx>.

Geiger, Abigail. "A Wider Ideological Gap between More and Less Educated Adults." *Pew Research Center - U.S. Politics & Policy*, Pew Research Center, 30 May 2020, <https://www.pewresearch.org/politics/2016/04/26/a-wider-ideological-gap-between-more-and-less-educated-adults/>.

Matthews, Dylan. "Sinclair, the pro-Trump, Conservative Company Taking over Local News, Explained." *Vox*, Vox, 3 Apr. 2018, <https://www.vox.com/2018/4/3/17180020/sinclair-broadcast-group-conservative-trump-david-smith-local-news-tv-affiliate>.

 Eisenger, Robert M, et al. "What Media Bias? Conservative and Liberal Labeling in Major US Newspapers." *Shibboleth Authentication Request*, 2007, <https://journals-sagepub-com.proxygw.wrlc.org/doi/pdf/10.1177/1081180X04263461>.  

Budak, Ceren and Goel, Sharad and Rao, Justin M., Fair and Balanced? Quantifying Media Bias through Crowdsourced Content Analysis (November 17, 2014). Available at SSRN: <https://ssrn.com/abstract=2526461> or [http://dx.doi.org/10.2139/ssrn.2526461](https://dx.doi.org/10.2139/ssrn.2526461)

Niven, David. "Bias in the News: Partisanship and Negativity in the Coverage of President's George Bush and Bill Clinton." *Harvard International Journal of Press / Politics*, vol. 6, 2001. 

Agirdas, Cagdas. "What Drives Media Bias? New Evidence From Recent Newspaper Closures." *Journal of Media Economics*, vol. 28, 2015, pp. 123--141.

Jones, David A. "Why Americans Don't Trust the Media." *Harvard International Journal of Press/Politics*, vol. 9, no. 2, 2004, pp. 60--75.,<https://doi.org/10.1177/1081180x04263461>.  
